-- MySQL Script generated by MySQL Workbench
-- Wed Sep 28 00:29:47 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema tallermecanico
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tallermecanico
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tallermecanico` DEFAULT CHARACTER SET utf8mb4 ;
USE `tallermecanico` ;

-- -----------------------------------------------------
-- Table `tallermecanico`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tallermecanico`.`usuarios` (
  `cedula` VARCHAR(20) NOT NULL,
  `nombres` VARCHAR(50) NOT NULL,
  `apellidos` VARCHAR(50) NOT NULL,
  `direccion` VARCHAR(50) NOT NULL,
  `telefono` VARCHAR(10) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `ciudad` CHAR(5) NOT NULL,
  `fechanac` DATE NOT NULL,
  `usuario` VARCHAR(15) NOT NULL,
  `clave` VARCHAR(100) NOT NULL,
  `estado` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`cedula`),
  UNIQUE INDEX `cedula_UNIQUE` (`cedula` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tallermecanico`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tallermecanico`.`roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `rol` VARCHAR(15) NOT NULL,
  `estado` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tallermecanico`.`detallesrol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tallermecanico`.`detallesrol` (
  `cedula` VARCHAR(20) NOT NULL,
  `rol` INT NOT NULL,
  `estado` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`cedula`, `rol`),
  INDEX `fk_detallesrol_usuarios_idx` (`cedula` ASC) ,
  INDEX `fk_detallesrol_roles1_idx` (`rol` ASC) ,
  CONSTRAINT `fk_detallesrol_usuarios`
    FOREIGN KEY (`cedula`)
    REFERENCES `tallermecanico`.`usuarios` (`cedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detallesrol_roles1`
    FOREIGN KEY (`rol`)
    REFERENCES `tallermecanico`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tallermecanico`.`especialidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tallermecanico`.`especialidades` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `especialidad` VARCHAR(20) NOT NULL,
  `estado` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tallermecanico`.`empleados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tallermecanico`.`empleados` (
  `cedula` VARCHAR(20) NOT NULL,
  `fechaingreso` DATE NOT NULL,
  `sueldo` INT NOT NULL DEFAULT 0,
  `especialidad` INT(2) NOT NULL,
  INDEX `fk_empleado_usuarios1_idx` (`cedula` ASC) ,
  PRIMARY KEY (`cedula`, `especialidad`),
  INDEX `fk_empleados_especialidades1_idx` (`especialidad` ASC) ,
  CONSTRAINT `fk_empleado_usuarios1`
    FOREIGN KEY (`cedula`)
    REFERENCES `tallermecanico`.`usuarios` (`cedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_empleados_especialidades1`
    FOREIGN KEY (`especialidad`)
    REFERENCES `tallermecanico`.`especialidades` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tallermecanico`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tallermecanico`.`clientes` (
  `cedula` VARCHAR(20) NOT NULL,
  `nombres` VARCHAR(50) NOT NULL,
  `apellidos` VARCHAR(50) NOT NULL,
  `direccion` VARCHAR(50) NOT NULL,
  `telefono` VARCHAR(10) NOT NULL,
  `email` VARCHAR(50) NULL,
  `ciudad` CHAR(5) NOT NULL,
  `fechanac` DATE NOT NULL,
  `estado` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`cedula`),
  UNIQUE INDEX `cedula_UNIQUE` (`cedula` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tallermecanico`.`tiposvehiculos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tallermecanico`.`tiposvehiculos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipovehiculo` VARCHAR(20) NOT NULL,
  `estado` INT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tallermecanico`.`vehiculos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tallermecanico`.`vehiculos` (
  `placa` VARCHAR(7) NOT NULL,
  `modelo` VARCHAR(20) NOT NULL,
  `color` VARCHAR(20) NOT NULL,
  `marca` VARCHAR(45) NOT NULL,
  `observacion` TEXT(1000) NULL,
  `estado` INT(1) NULL DEFAULT 1,
  `propierario` VARCHAR(20) NOT NULL,
  `tipovehiculo` INT NOT NULL,
  PRIMARY KEY (`placa`),
  INDEX `fk_vehiculos_clientes1_idx` (`propierario` ASC) ,
  INDEX `fk_vehiculos_tiposvehiculos1_idx` (`tipovehiculo` ASC) ,
  CONSTRAINT `fk_vehiculos_clientes1`
    FOREIGN KEY (`propierario`)
    REFERENCES `tallermecanico`.`clientes` (`cedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vehiculos_tiposvehiculos1`
    FOREIGN KEY (`tipovehiculo`)
    REFERENCES `tallermecanico`.`tiposvehiculos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tallermecanico`.`cat_producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tallermecanico`.`cat_producto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `categoria` VARCHAR(20) NOT NULL,
  `eatado` INT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tallermecanico`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tallermecanico`.`productos` (
  `codigo` CHAR(5) NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `categoria` INT NOT NULL,
  `fechaingreso` DATE NOT NULL,
  `preciocompra` INT NOT NULL,
  `precioventa` INT NOT NULL,
  `stock` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`codigo`),
  INDEX `fk_productos_cat_producto1_idx` (`categoria` ASC) ,
  CONSTRAINT `fk_productos_cat_producto1`
    FOREIGN KEY (`categoria`)
    REFERENCES `tallermecanico`.`cat_producto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tallermecanico`.`tipostrabajos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tallermecanico`.`tipostrabajos` (
  `id` INT NOT NULL,
  `tipotrabajo` VARCHAR(20) NOT NULL,
  `estado` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tallermecanico`.`planillaingresos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tallermecanico`.`planillaingresos` (
  `id` INT NOT NULL,
  `cliente` VARCHAR(20) NOT NULL,
  `fechaingreso` DATE NOT NULL,
  `fechaentrega` DATE NOT NULL,
  `placavehiculo` VARCHAR(7) NOT NULL,
  `descripciontrabajo` VARCHAR(45) NOT NULL,
  `observacion` TEXT(1000) NULL,
  `empleado` VARCHAR(20) NOT NULL,
  `tipotrabajo` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_plantillaingresos_clientes1_idx` (`cliente` ASC) ,
  INDEX `fk_planillaingresos_empleados1_idx` (`empleado` ASC) ,
  INDEX `fk_planillaingresos_tipostrabajos1_idx` (`tipotrabajo` ASC) ,
  CONSTRAINT `fk_plantillaingresos_clientes1`
    FOREIGN KEY (`cliente`)
    REFERENCES `tallermecanico`.`clientes` (`cedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_planillaingresos_empleados1`
    FOREIGN KEY (`empleado`)
    REFERENCES `tallermecanico`.`empleados` (`cedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_planillaingresos_tipostrabajos1`
    FOREIGN KEY (`tipotrabajo`)
    REFERENCES `tallermecanico`.`tipostrabajos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tallermecanico`.`formaspago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tallermecanico`.`formaspago` (
  `id` INT NOT NULL,
  `formapago` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tallermecanico`.`facturas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tallermecanico`.`facturas` (
  `numfactura` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `cajero` VARCHAR(20) NOT NULL,
  `planilla` INT NOT NULL,
  `totalapagar` FLOAT(11,2) NOT NULL,
  `descuentos` FLOAT(11,2) NOT NULL,
  `observacion` TEXT(1000) NULL,
  `formadepago` INT NOT NULL,
  PRIMARY KEY (`numfactura`),
  INDEX `fk_facturas_usuarios1_idx` (`cajero` ASC) ,
  INDEX `fk_facturas_planillaingresos1_idx` (`planilla` ASC) ,
  INDEX `fk_facturas_formaspago1_idx` (`formadepago` ASC) ,
  CONSTRAINT `fk_facturas_usuarios1`
    FOREIGN KEY (`cajero`)
    REFERENCES `tallermecanico`.`usuarios` (`cedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_facturas_planillaingresos1`
    FOREIGN KEY (`planilla`)
    REFERENCES `tallermecanico`.`planillaingresos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_facturas_formaspago1`
    FOREIGN KEY (`formadepago`)
    REFERENCES `tallermecanico`.`formaspago` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tallermecanico`.`facturacionproductos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tallermecanico`.`facturacionproductos` (
  `codigoproducto` CHAR(5) NOT NULL,
  `numfactura` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `estado` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`codigoproducto`, `numfactura`),
  INDEX `fk_cantidadproductos_productos1_idx` (`codigoproducto` ASC) ,
  INDEX `fk_facturacionproductos_facturas1_idx` (`numfactura` ASC) ,
  CONSTRAINT `fk_cantidadproductos_productos1`
    FOREIGN KEY (`codigoproducto`)
    REFERENCES `tallermecanico`.`productos` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_facturacionproductos_facturas1`
    FOREIGN KEY (`numfactura`)
    REFERENCES `tallermecanico`.`facturas` (`numfactura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tallermecanico`.`facturacioncredito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tallermecanico`.`facturacioncredito` (
  `numfactura` INT NOT NULL,
  `tiempofinanciacion` INT NOT NULL,
  `tasainteres` INT NOT NULL,
  `interes` FLOAT(3,2) NOT NULL,
  PRIMARY KEY (`numfactura`),
  INDEX `fk_facturacioncredito_facturas1_idx` (`numfactura` ASC) ,
  CONSTRAINT `fk_facturacioncredito_facturas1`
    FOREIGN KEY (`numfactura`)
    REFERENCES `tallermecanico`.`facturas` (`numfactura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- POBLAR DATOS BASICOS
-- -----------------------------------------------------
-- DATOS PRIMER ADMIN
INSERT INTO `usuarios`(
  `cedula`, `nombres`, `apellidos`, `direccion`, `telefono`, `email`, `ciudad`, `fechanac`, `usuario`, `clave`
  ) VALUES (
  '1006962289', 'Yorth Harbin', 'Ortegon Sanchez', 'Pasto', '3229363914',
  'yorth@udenar.edu.co', '52001', '2002-09-21', 'admin', 'admin'
);

INSERT INTO `roles`(`rol`) VALUES ('administrador'),('empleado');

INSERT INTO `detallesrol`(`cedula`, `rol`) VALUES ('1006962289', 1);

-- DATOS BASICOS PARA LE FUNCIONAMIENTO

INSERT INTO `tiposvehiculos`(`tipovehiculo`) VALUES ('moto'),('automóvil'),('camioneta'),('camión');

INSERT INTO `especialidades`(`especialidad`) VALUES ('moto'),('automóvil'),('camioneta'),('camión');